"""empty message

Revision ID: 0c4ea958328a
Revises: bdb0474bf546
Create Date: 2022-07-31 17:04:29.092542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4ea958328a'
down_revision = 'bdb0474bf546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdetail',
    sa.Column('id_detail', sa.Integer(), nullable=False),
    sa.Column('user_image', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_detail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdetail')
    # ### end Alembic commands ###
