"""empty message

Revision ID: 513f39cdfc76
Revises: cb399ca2247f
Create Date: 2022-08-03 12:36:19.330068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513f39cdfc76'
down_revision = 'cb399ca2247f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userevent', sa.Column('event_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userevent', 'event_image')
    # ### end Alembic commands ###
