"""empty message

Revision ID: ca0b349f5bb5
Revises: a69a09a9eadd
Create Date: 2022-07-06 19:22:30.316948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0b349f5bb5'
down_revision = 'a69a09a9eadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beer', 'image',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('beer', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('beer', 'smell',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('beer', 'source',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('beer', 'alcohol',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('beer', 'company',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('beer', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('beer', 'creation_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beer', 'creation_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('beer', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('beer', 'company',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('beer', 'alcohol',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('beer', 'source',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('beer', 'smell',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('beer', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('beer', 'image',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
